/*
 * File Name: cql2_lexer-internal.h
 *
 * Copyright (c) 2024 IndoorSpatial
 *
 * Author: Kunlin Yu <yukunlin@syriusrobotics.com>
 * Create Date: 2024/12/19
 *
 */

#pragma once

#include <cql2cpp/cql2_parser_base.hh>
#include <istream>
#include <ostream>

// This file will be part of cc file generated by flex++.
// And the #include<FlexLexer.h> will appear above this file
// https://stackoverflow.com/questions/71300080/change-yylex-in-c-flex
class Cql2Lexer : public yyFlexLexer {
 private:
  cql2cpp::Cql2ParserBase::value_type* yylval_;

 public:
  Cql2Lexer() : yyFlexLexer() {}

  Cql2Lexer(std::istream& ins, std::ostream& ous) : yyFlexLexer(ins, ous) {}

  int yylex();

  void set_yylval(cql2cpp::Cql2ParserBase::value_type* yylval) { yylval_ = yylval; }

};
