/*
 * File Name: cql2_lexer-internal.h
 *
 * Copyright (c) 2024 IndoorSpatial
 *
 * Author: Kunlin Yu <yukunlin@syriusrobotics.com>
 * Create Date: 2024/12/19
 *
 */

#pragma once

// This file will be part of cc file generated by flex++.
// And the #include<FlexLexer.h> will appear above this file
// https://stackoverflow.com/questions/71300080/change-yylex-in-c-flex
class Cql2Lexer : public yyFlexLexer {
  public:
    int yylex();
};
